
name: Run Market Monitor

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点（北京时间8点）运行
  push:
    paths:
      - 'analysis_report.md'  # 当analysis_report.md更新时触发
      - 'market_monitor.py'
  workflow_dispatch:  # 支持手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # 与fund_analyzer.py一致

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-get clean
          echo "Apt update completed successfully"
        env:
          DEBIAN_FRONTEND: noninteractive
        continue-on-error: true

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pandas numpy akshare
          python -c "import akshare as ak; print('AKShare version:', ak.__version__)"
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.10.18/x64

      - name: Verify files exist
        run: |
          if [ ! -f analysis_report.md ]; then
            echo "Error: analysis_report.md not found!"
            exit 1
          fi
          if [ ! -f market_monitor.py ]; then
            echo "Error: market_monitor.py not found!"
            exit 1
          fi
          echo "Required files found: analysis_report.md, market_monitor.py"

      - name: Test AKShare interface
        run: |
          python -c "import akshare as ak; df = ak.fund_open_fund_info_em(symbol='007509', indicator='累计净值走势'); print(df.head())" || echo "AKShare test failed, check parameters"

      - name: Run Market Monitor script
        run: |
          python market_monitor.py || echo "Script failed, check market_monitor.log"

      - name: Commit and push results
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add market_monitor_report.md market_monitor.log || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update market monitor report and log - $(date)"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Check for errors in log
        if: always()
        run: |
          if [ -f market_monitor.log ]; then
            if grep -i "ERROR" market_monitor.log; then
              echo "Errors found in log:"
              grep -i "ERROR" market_monitor.log
              exit 1
            else
              echo "No errors found in log. Success!"
            fi
          else
            echo "market_monitor.log not found"
            exit 1
          fi
