name: Run Market Monitor

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点（北京时间8点）运行
  push:
    paths:
      - 'analysis_report.md'  # 当analysis_report.md更新时触发
  workflow_dispatch:  # 支持手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # 与fund_analyzer.py一致

      - name: Install system dependencies and optimize apt
        run: |
          sudo apt-get update --timeout=60 || true  # 添加超时，容错失败
          sudo apt-get install -y software-properties-common  # 确保基本工具
          sudo apt-get clean  # 清理缓存，避免空间问题
          echo "Apt update completed successfully"
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pandas numpy akshare  # 确保akshare最新版
          python -c "import akshare as ak; print(ak.__version__)"  # 验证akshare版本

      # 可选：如果未来需要Selenium，再取消注释此步骤
      # - name: Install Chromium and ChromeDriver
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y chromium-browser chromium-chromedriver wget unzip
      #     sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome  # 链接以兼容Selenium
      #     chromedriver --version || echo "ChromeDriver installation may have issues"
      #   env:
      #     DEBIAN_FRONTEND: noninteractive

      - name: Verify analysis_report.md exists
        run: |
          if [ ! -f analysis_report.md ]; then
            echo "analysis_report.md not found! Exiting."
            exit 1
          else
            echo "analysis_report.md found. Proceeding."
          fi

      - name: Run Market Monitor script
        run: |
          python market_monitor.py || echo "Script failed, check market_monitor.log"

      - name: Commit and push results
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add market_monitor_report.md market_monitor.log
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update market monitor report and log - $(date)"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Check for errors in log
        if: always()  # 始终运行，即使失败
        run: |
          if [ -f market_monitor.log ]; then
            if grep -i "ERROR" market_monitor.log; then
              echo "Errors found in log:"
              grep -i "ERROR" market_monitor.log
              exit 1
            else
              echo "No errors found in log. Success!"
            fi
          else
            echo "market_monitor.log not found"
            exit 1
          fi
